name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"

  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"

  - title: "📚 Documentation"
    labels:
      - "documentation"

  - title: "🧰 Maintenance"
    labels:
      - "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - breaking
      - major

  minor:
    labels:
      - feature
      - enhancement
      - minor

  patch:
    labels:
      - patch
      - bug
      - bugfix
      - fix
      - documentation
      - chore

  default: patch

template: |
  ## Changes

  $CHANGES
